USE PublicData
GO

CREATE TABLE Countries
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE States
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	CountryId INT REFERENCES Countries(Id),
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Cities
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	StateId INT REFERENCES States(Id),
	[Name] VARCHAR(50) NOT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Organizations
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[Address] VARCHAR(250) NULL,
	PanNo VARCHAR(15) NULL,
	IsNasscomRegistered BIT NOT NULL DEFAULT 0,
	LongText VARCHAR(500) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Headers
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	OrganizationId INT REFERENCES Organizations(Id) NOT NULL,
	Title VARCHAR(50) NOT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Departments
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	OrganizationId INT REFERENCES Organizations(Id) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	StartedAt DATE NULL,
	LongText VARCHAR(500) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Details
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	HeaderId INT REFERENCES Headers(Id),
	[Value] VARCHAR(100) NOT NULL,
	ExtraField VARCHAR(250) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE People
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonTypeId INT REFERENCES Details(Id) NOT NULL,	-- it was regular, etc, now it is Yuvak or wardhak etc
	OrganizationId INT REFERENCES Organizations(Id) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	MiddleName VARCHAR(50) NULL,
	LastName VARCHAR(50) NOT NULL,
	BirthDate DATE NULL,
	BirthLocation VARCHAR(50) NULL,
	LongText VARCHAR(500) NULL,
	Keywords VARCHAR(250) NULL,
	IsWorker BIT NOT NULL DEFAULT 0,	-- is he / she working, so that we can assign him work
	WorkFrequency INT REFERENCES Details(Id) NOT NULL,	-- it will be daily, periodic, rare, etc
	JoiningDate DATE NULL,
	JoinedAsId INT REFERENCES Details(Id) NULL,
	CountryId INT REFERENCES Countries(Id) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE DepartmentHeads
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	DepartmentId INT REFERENCES Departments(Id) NOT NULL,
	FromYear INT NOT NULL,
	ToYear INT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Divisions
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DepartmentId INT REFERENCES Departments(Id) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[Address] VARCHAR(250) NOT NULL,
	StartDate DATE NOT NULL,
	LongText VARCHAR(500) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE DivisionHeads
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	DivisionId INT REFERENCES Divisions(Id) NOT NULL,
	FromYear INT NOT NULL,
	ToYear INT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonPrivateInformations
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	PersonId INT REFERENCES People(Id) NOT NULL,
	MaritalStatus BIT NOT NULL DEFAULT 0,
	AadharCardNo VARCHAR(15) NULL,
	IsOwnBicycle BIT NOT NULL DEFAULT 0,
	ReligionId INT REFERENCES Details(Id) NULL,
	CasteId INT REFERENCES Details(Id) NULL,
	ParentalStatusId INT REFERENCES Details(Id) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonAchievements
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NULL,
	Title VARCHAR(50) NOT NULL,
	GivenBy VARCHAR(100) NULL,
	[Format] VARCHAR(50) NULL,
	Reason VARCHAR(50) NULL,
	ReceivedDate DATE NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonAddresses
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	CountryId INT REFERENCES Countries(Id) NULL,
	StateId INT REFERENCES States(Id) NULL,
	CityId INT REFERENCES Cities(Id) NULL,
	IsPermanent BIT NOT NULL,
	RoadName VARCHAR(25) NULL,
	Line1 VARCHAR(100) NULL,
	Line2 VARCHAR(100) NULL,
	ZipCode VARCHAR(10) NULL,
	FromYear INT NULL,
	ToYear INT NULL,
	RoomsInHome INT NULL,
	IsGovtBuildUp BIT NOT NULL DEFAULT 0,
	HomeStatusId INT REFERENCES Details(Id) NULL,
	LocalityClass INT REFERENCES Details(Id) NULL,
	ResidentialStatus INT REFERENCES Details(Id) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonContacts
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	ContactType INT REFERENCES Details(Id) NULL,
	Detail VARCHAR(100),
	IsDefault BIT NOT NULL DEFAULT 0, 
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonDisabilities
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	Problem VARCHAR(50) NOT NULL,
	Detail VARCHAR(250) NULL,
	FromYear INT NULL,
	ToYear INT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonEducations
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	SchoolId INT REFERENCES Details(Id) NULL,
	FromStdId INT REFERENCES Details(Id) NULL,
	ToStdId INT REFERENCES Details(Id) NULL,
	FromYear INT NOT NULL,
	ToYear INT NULL,
	UniversityBoardId INT REFERENCES Details(Id) NULL,
	DegreeId INT REFERENCES Details(Id) NULL,
	CourseId INT REFERENCES Details(Id) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonFamilyDetails
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	MiddleName VARCHAR(50) NULL,
	LastName VARCHAR(50) NOT NULL,
	BirthDate DATE NULL,
	MobileNo VARCHAR(15) NULL,
	Email VARCHAR(50) NULL,
	CompanyName VARCHAR(50) NULL,
	SchoolName VARCHAR(50) NULL,
	MonthlyIncome FLOAT NULL,
	PersonId INT REFERENCES People(Id) NULL,
	RelationId INT REFERENCES Details(Id) NULL,
	CourseId INT REFERENCES Details(Id) NULL,
	AnyDisability VARCHAR(100) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonHealthDetails
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	Height FLOAT NULL,
	[Weight] FLOAT NULL,
	IQ FLOAT NULL,
	WakeUpTiming FLOAT NULL,
	SleepTiming FLOAT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonHobbyFavorites
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	HobbyFavoriteId INT REFERENCES Details(Id) NULL,
	LongText VARCHAR(500) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonLanguages
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	LanguageId INT REFERENCES Details(Id) NOT NULL,
	IsMotherTongue BIT NOT NULL DEFAULT 0,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonSocialMediaAccounts
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	AccountTypeId INT REFERENCES Details(Id) NOT NULL,
	Link VARCHAR(50) NULL,
	TypeOfUserId INT REFERENCES Details(Id) NOT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE PersonWorkExperiences
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	IndustryId INT REFERENCES Details(Id) NOT NULL,
	WorkTypeId INT REFERENCES Details(Id) NULL,
	CompanyName VARCHAR(50) NULL,
	ActualWork VARCHAR(50) NULL,
	FromYear INT NULL,
	ToYear INT NULL,
	LongText VARCHAR(500) NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Universities
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	CityId INT REFERENCES Cities(Id) NOT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Programs
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	OrganizationId INT REFERENCES Organizations(Id) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE Tickets
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

CREATE TABLE ProgramAttendances
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PersonId INT REFERENCES People(Id) NOT NULL,
	ProgramId INT REFERENCES Programs(Id) NOT NULL,
	CreatedById NVARCHAR(450) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedById NVARCHAR(450) NULL,
	UpdatedAt DATETIME NULL,
	DeletedById NVARCHAR(450) NULL,
	DeletedAt DATETIME NULL
)
GO

--CREATE TABLE School
--(
--	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
--	[Name] VARCHAR(50) NOT NULL,
--	[Address] VARCHAR(100) NULL,
--	CreatedById NVARCHAR(450) NOT NULL,
--	CreatedAt DATETIME NOT NULL,
--	UpdatedById NVARCHAR(450) NULL,
--	UpdatedAt DATETIME NULL,
--	DeletedById NVARCHAR(450) NULL,
--	DeletedAt DATETIME NULL
--)
--GO

--CREATE TABLE Industry
--(
--	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
--	[Name] VARCHAR(50) NOT NULL,
--	LongText VARCHAR(500) NULL,
--	CreatedById NVARCHAR(450) NOT NULL,
--	CreatedAt DATETIME NOT NULL,
--	UpdatedById NVARCHAR(450) NULL,
--	UpdatedAt DATETIME NULL,
--	DeletedById NVARCHAR(450) NULL,
--	DeletedAt DATETIME NULL
--)
--GO
