<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\PersonFamilyDetail\CreatePersonEducation\**" />
    <Compile Remove="Features\PersonFamilyDetail\DeletePersonEducationByEducationId\**" />
    <Compile Remove="Features\PersonFamilyDetail\DeletePersonEducationByPersonId\**" />
    <Compile Remove="Features\PersonFamilyDetail\GetPersonAllEducations\**" />
    <Compile Remove="Features\PersonFamilyDetail\GetPersonEducationByEducationId\**" />
    <Compile Remove="Features\PersonFamilyDetail\UpdatePersonEducationByEducationId\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\CreatePersonEducation\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\DeletePersonEducationByEducationId\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\DeletePersonEducationByPersonId\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\GetPersonAllEducations\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\GetPersonEducationByEducationId\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\UpdatePersonEducationByEducationId\**" />
    <None Remove="Features\PersonFamilyDetail\CreatePersonEducation\**" />
    <None Remove="Features\PersonFamilyDetail\DeletePersonEducationByEducationId\**" />
    <None Remove="Features\PersonFamilyDetail\DeletePersonEducationByPersonId\**" />
    <None Remove="Features\PersonFamilyDetail\GetPersonAllEducations\**" />
    <None Remove="Features\PersonFamilyDetail\GetPersonEducationByEducationId\**" />
    <None Remove="Features\PersonFamilyDetail\UpdatePersonEducationByEducationId\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="FluentValidation" Version="9.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="9.1.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="8.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PublicData.DAL\PublicData.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Master\Batch\" />
    <Folder Include="Features\Master\Course\" />
    <Folder Include="Features\Master\CourseHead\" />
    <Folder Include="Features\Master\Event\" />
    <Folder Include="Features\Master\Ticket\" />
    <Folder Include="Features\Master\SubProgram\" />
  </ItemGroup>

</Project>
