<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\PersonFamilyDetail\CreatePersonEducation\**" />
    <Compile Remove="Features\PersonFamilyDetail\DeletePersonEducationByEducationId\**" />
    <Compile Remove="Features\PersonFamilyDetail\DeletePersonEducationByPersonId\**" />
    <Compile Remove="Features\PersonFamilyDetail\GetPersonAllEducations\**" />
    <Compile Remove="Features\PersonFamilyDetail\GetPersonEducationByEducationId\**" />
    <Compile Remove="Features\PersonFamilyDetail\UpdatePersonEducationByEducationId\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\CreatePersonEducation\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\DeletePersonEducationByEducationId\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\DeletePersonEducationByPersonId\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\GetPersonAllEducations\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\GetPersonEducationByEducationId\**" />
    <EmbeddedResource Remove="Features\PersonFamilyDetail\UpdatePersonEducationByEducationId\**" />
    <None Remove="Features\PersonFamilyDetail\CreatePersonEducation\**" />
    <None Remove="Features\PersonFamilyDetail\DeletePersonEducationByEducationId\**" />
    <None Remove="Features\PersonFamilyDetail\DeletePersonEducationByPersonId\**" />
    <None Remove="Features\PersonFamilyDetail\GetPersonAllEducations\**" />
    <None Remove="Features\PersonFamilyDetail\GetPersonEducationByEducationId\**" />
    <None Remove="Features\PersonFamilyDetail\UpdatePersonEducationByEducationId\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="FluentValidation" Version="8.6.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="8.6.2" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PublicData.Common\PublicData.Common.csproj" />
    <ProjectReference Include="..\PublicData.DAL\PublicData.DAL.csproj" />
  </ItemGroup>

</Project>
